// Generated by cargo-carapace from the GoodNightEngine core schema. Do not edit.
// Regenerate with: cargo carapace gen swift

import Foundation
import CarapaceKit

public enum GoodNightEngine: CarapaceApp {
    public static let name = "GoodNightEngine"
    public static let schemaHash: UInt64 = 0xd31400e8f1c7868c


    public struct PresetInfo: Codable, Sendable, Hashable {
        public var name: String
        public var level: Double
        public var kelvin: Int

        public init(name: String, level: Double, kelvin: Int) {
            self.name = name
            self.level = level
            self.kelvin = kelvin
        }
    }

    /// What the screen should show right now.
    public struct Target: Codable, Sendable, Hashable {
        public var level: Double
        public var brightness: Double

        public init(level: Double, brightness: Double) {
            self.level = level
            self.brightness = brightness
        }
    }

    /// Everything the UI renders. Times are unix milliseconds so each UI formats them in the user's locale.
    public struct State: Codable, Sendable, Hashable {
        public var enabled: Bool
        public var followSun: Bool
        public var autoUpdate: Bool
        /// The warmth the user sees and edits, 0 (no tint) … 1 (deep night).
        public var level: Double
        public var brightness: Double
        public var kelvin: Int
        /// Name of the preset nearest to `level`.
        public var preset: String
        public var presets: [PresetInfo]
        /// What the display should actually show: no tint and full brightness when switched off.
        public var target: Target
        public var placeName: String
        public var sunrise: Double
        public var sunset: Double
        public var nextWarms: Bool
        public var nextAt: Double

        public init(enabled: Bool, followSun: Bool, autoUpdate: Bool, level: Double, brightness: Double, kelvin: Int, preset: String, presets: [PresetInfo], target: Target, placeName: String, sunrise: Double, sunset: Double, nextWarms: Bool, nextAt: Double) {
            self.enabled = enabled
            self.followSun = followSun
            self.autoUpdate = autoUpdate
            self.level = level
            self.brightness = brightness
            self.kelvin = kelvin
            self.preset = preset
            self.presets = presets
            self.target = target
            self.placeName = placeName
            self.sunrise = sunrise
            self.sunset = sunset
            self.nextWarms = nextWarms
            self.nextAt = nextAt
        }
    }

    public indirect enum Action: Sendable, Hashable {
        /// `animated: false` while a slider is being dragged.
        case setLevel(level: Double, animated: Bool)
        case setBrightness(value: Double, animated: Bool)
        /// Relative change from the shortcuts. Both are animated.
        case nudge(level: Double, brightness: Double)
        case setEnabled(on: Bool)
        case setFollowSun(on: Bool)
        case setAutoUpdate(on: Bool)
        /// The system time zone changed (travel, daylight saving).
        case setTimeZone(zone: String, utcOffsetSeconds: Int)
        /// Re-read the clock: after wake from sleep, or from the core's own minute timer.
        case refresh
    }

    /// What is saved between launches. Same meaning on every platform.
    public struct Settings: Codable, Sendable, Hashable {
        public var enabled: Bool
        public var followSun: Bool
        /// Warmth when not following the sun.
        public var manualLevel: Double
        /// Warmth by day when following the sun.
        public var dayLevel: Double
        /// Warmth by night when following the sun.
        public var nightLevel: Double
        public var brightness: Double
        public var autoUpdate: Bool

        public init(enabled: Bool = true, followSun: Bool = true, manualLevel: Double = 0.45, dayLevel: Double = 0.0, nightLevel: Double = 0.68, brightness: Double = 1.0, autoUpdate: Bool = true) {
            self.enabled = enabled
            self.followSun = followSun
            self.manualLevel = manualLevel
            self.dayLevel = dayLevel
            self.nightLevel = nightLevel
            self.brightness = brightness
            self.autoUpdate = autoUpdate
        }

        enum CodingKeys: Swift.String, Swift.CodingKey {
            case enabled
            case followSun
            case manualLevel
            case dayLevel
            case nightLevel
            case brightness
            case autoUpdate
        }

        public init(from decoder: Swift.Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            self.enabled = try c.decodeIfPresent(Bool.self, forKey: .enabled) ?? true
            self.followSun = try c.decodeIfPresent(Bool.self, forKey: .followSun) ?? true
            self.manualLevel = try c.decodeIfPresent(Double.self, forKey: .manualLevel) ?? 0.45
            self.dayLevel = try c.decodeIfPresent(Double.self, forKey: .dayLevel) ?? 0.0
            self.nightLevel = try c.decodeIfPresent(Double.self, forKey: .nightLevel) ?? 0.68
            self.brightness = try c.decodeIfPresent(Double.self, forKey: .brightness) ?? 1.0
            self.autoUpdate = try c.decodeIfPresent(Bool.self, forKey: .autoUpdate) ?? true
        }
    }

    public struct Config: Codable, Sendable, Hashable {
        /// Saved settings from the last run.
        public var settings: Settings?
        /// IANA name of the system time zone, e.g. "America/New_York".
        public var timeZone: String
        /// Current offset of the system time zone from UTC, in seconds.
        public var utcOffsetSeconds: Int
        /// Freeze the clock at this unix time (seconds). For tests and screenshots only.
        public var fixedNow: Double?

        public init(settings: Settings? = nil, timeZone: String = "", utcOffsetSeconds: Int = 0, fixedNow: Double? = nil) {
            self.settings = settings
            self.timeZone = timeZone
            self.utcOffsetSeconds = utcOffsetSeconds
            self.fixedNow = fixedNow
        }

        enum CodingKeys: Swift.String, Swift.CodingKey {
            case settings
            case timeZone
            case utcOffsetSeconds
            case fixedNow
        }

        public init(from decoder: Swift.Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            self.settings = try c.decodeIfPresent(Settings.self, forKey: .settings)
            self.timeZone = try c.decodeIfPresent(String.self, forKey: .timeZone) ?? ""
            self.utcOffsetSeconds = try c.decodeIfPresent(Int.self, forKey: .utcOffsetSeconds) ?? 0
            self.fixedNow = try c.decodeIfPresent(Double.self, forKey: .fixedNow)
        }
    }

    public indirect enum Event: Sendable, Hashable {
        /// Put `state.target` on the screen, easing over a second when `animated`.
        case render(animated: Bool)
        /// Save these settings.
        case persist(settings: Settings)
    }

    public indirect enum Query: Sendable, Hashable {
        /// Colour numbers for one warmth level.
        case warmth(level: Double)
        /// The full tint for one display: its own calibration curve (three tables of 0…1) in, the
        /// ramp to apply out.
        case ramp(level: Double, brightness: Double, r: [Double], g: [Double], b: [Double])
    }

    public indirect enum Answer: Sendable, Hashable {
        case warmth(kelvin: Double, kelvinLabel: Int, dim: Double, gains: [Double], tint: [Double])
        case ramp(r: [Double], g: [Double], b: [Double])
    }

}

extension GoodNightEngine.Action: Codable {
    private struct Key: Swift.CodingKey {
        var stringValue: String
        var intValue: Int? { nil }
        init(_ s: String) { stringValue = s }
        init?(stringValue: String) { self.stringValue = stringValue }
        init?(intValue: Int) { nil }
    }

    public init(from decoder: Swift.Decoder) throws {
        let c = try decoder.container(keyedBy: Key.self)
        let tag = try c.decode(String.self, forKey: Key("type"))
        switch tag {
        case "setLevel":
            let v0 = try c.decode(Double.self, forKey: Key("level"))
            let v1 = try c.decode(Bool.self, forKey: Key("animated"))
            self = .setLevel(level: v0, animated: v1)
        case "setBrightness":
            let v0 = try c.decode(Double.self, forKey: Key("value"))
            let v1 = try c.decode(Bool.self, forKey: Key("animated"))
            self = .setBrightness(value: v0, animated: v1)
        case "nudge":
            let v0 = try c.decode(Double.self, forKey: Key("level"))
            let v1 = try c.decode(Double.self, forKey: Key("brightness"))
            self = .nudge(level: v0, brightness: v1)
        case "setEnabled":
            let v0 = try c.decode(Bool.self, forKey: Key("on"))
            self = .setEnabled(on: v0)
        case "setFollowSun":
            let v0 = try c.decode(Bool.self, forKey: Key("on"))
            self = .setFollowSun(on: v0)
        case "setAutoUpdate":
            let v0 = try c.decode(Bool.self, forKey: Key("on"))
            self = .setAutoUpdate(on: v0)
        case "setTimeZone":
            let v0 = try c.decode(String.self, forKey: Key("zone"))
            let v1 = try c.decode(Int.self, forKey: Key("utc_offset_seconds"))
            self = .setTimeZone(zone: v0, utcOffsetSeconds: v1)
        case "refresh": self = .refresh
        default:
            throw Swift.DecodingError.dataCorruptedError(forKey: Key("type"), in: c, debugDescription: "unknown Action type \(tag)")
        }
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var c = encoder.container(keyedBy: Key.self)
        switch self {
        case .setLevel(let v0, let v1):
            try c.encode("setLevel", forKey: Key("type"))
            try c.encode(v0, forKey: Key("level"))
            try c.encode(v1, forKey: Key("animated"))
        case .setBrightness(let v0, let v1):
            try c.encode("setBrightness", forKey: Key("type"))
            try c.encode(v0, forKey: Key("value"))
            try c.encode(v1, forKey: Key("animated"))
        case .nudge(let v0, let v1):
            try c.encode("nudge", forKey: Key("type"))
            try c.encode(v0, forKey: Key("level"))
            try c.encode(v1, forKey: Key("brightness"))
        case .setEnabled(let v0):
            try c.encode("setEnabled", forKey: Key("type"))
            try c.encode(v0, forKey: Key("on"))
        case .setFollowSun(let v0):
            try c.encode("setFollowSun", forKey: Key("type"))
            try c.encode(v0, forKey: Key("on"))
        case .setAutoUpdate(let v0):
            try c.encode("setAutoUpdate", forKey: Key("type"))
            try c.encode(v0, forKey: Key("on"))
        case .setTimeZone(let v0, let v1):
            try c.encode("setTimeZone", forKey: Key("type"))
            try c.encode(v0, forKey: Key("zone"))
            try c.encode(v1, forKey: Key("utc_offset_seconds"))
        case .refresh:
            try c.encode("refresh", forKey: Key("type"))
        }
    }
}

extension GoodNightEngine.Event: Codable {
    private struct Key: Swift.CodingKey {
        var stringValue: String
        var intValue: Int? { nil }
        init(_ s: String) { stringValue = s }
        init?(stringValue: String) { self.stringValue = stringValue }
        init?(intValue: Int) { nil }
    }

    public init(from decoder: Swift.Decoder) throws {
        let c = try decoder.container(keyedBy: Key.self)
        let tag = try c.decode(String.self, forKey: Key("type"))
        switch tag {
        case "render":
            let v0 = try c.decode(Bool.self, forKey: Key("animated"))
            self = .render(animated: v0)
        case "persist":
            let v0 = try c.decode(GoodNightEngine.Settings.self, forKey: Key("settings"))
            self = .persist(settings: v0)
        default:
            throw Swift.DecodingError.dataCorruptedError(forKey: Key("type"), in: c, debugDescription: "unknown Event type \(tag)")
        }
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var c = encoder.container(keyedBy: Key.self)
        switch self {
        case .render(let v0):
            try c.encode("render", forKey: Key("type"))
            try c.encode(v0, forKey: Key("animated"))
        case .persist(let v0):
            try c.encode("persist", forKey: Key("type"))
            try c.encode(v0, forKey: Key("settings"))
        }
    }
}

extension GoodNightEngine.Query: Codable {
    private struct Key: Swift.CodingKey {
        var stringValue: String
        var intValue: Int? { nil }
        init(_ s: String) { stringValue = s }
        init?(stringValue: String) { self.stringValue = stringValue }
        init?(intValue: Int) { nil }
    }

    public init(from decoder: Swift.Decoder) throws {
        let c = try decoder.container(keyedBy: Key.self)
        let tag = try c.decode(String.self, forKey: Key("type"))
        switch tag {
        case "warmth":
            let v0 = try c.decode(Double.self, forKey: Key("level"))
            self = .warmth(level: v0)
        case "ramp":
            let v0 = try c.decode(Double.self, forKey: Key("level"))
            let v1 = try c.decode(Double.self, forKey: Key("brightness"))
            let v2 = try c.decode([Double].self, forKey: Key("r"))
            let v3 = try c.decode([Double].self, forKey: Key("g"))
            let v4 = try c.decode([Double].self, forKey: Key("b"))
            self = .ramp(level: v0, brightness: v1, r: v2, g: v3, b: v4)
        default:
            throw Swift.DecodingError.dataCorruptedError(forKey: Key("type"), in: c, debugDescription: "unknown Query type \(tag)")
        }
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var c = encoder.container(keyedBy: Key.self)
        switch self {
        case .warmth(let v0):
            try c.encode("warmth", forKey: Key("type"))
            try c.encode(v0, forKey: Key("level"))
        case .ramp(let v0, let v1, let v2, let v3, let v4):
            try c.encode("ramp", forKey: Key("type"))
            try c.encode(v0, forKey: Key("level"))
            try c.encode(v1, forKey: Key("brightness"))
            try c.encode(v2, forKey: Key("r"))
            try c.encode(v3, forKey: Key("g"))
            try c.encode(v4, forKey: Key("b"))
        }
    }
}

extension GoodNightEngine.Answer: Codable {
    private struct Key: Swift.CodingKey {
        var stringValue: String
        var intValue: Int? { nil }
        init(_ s: String) { stringValue = s }
        init?(stringValue: String) { self.stringValue = stringValue }
        init?(intValue: Int) { nil }
    }

    public init(from decoder: Swift.Decoder) throws {
        let c = try decoder.container(keyedBy: Key.self)
        let tag = try c.decode(String.self, forKey: Key("type"))
        switch tag {
        case "warmth":
            let v0 = try c.decode(Double.self, forKey: Key("kelvin"))
            let v1 = try c.decode(Int.self, forKey: Key("kelvinLabel"))
            let v2 = try c.decode(Double.self, forKey: Key("dim"))
            let v3 = try c.decode([Double].self, forKey: Key("gains"))
            let v4 = try c.decode([Double].self, forKey: Key("tint"))
            self = .warmth(kelvin: v0, kelvinLabel: v1, dim: v2, gains: v3, tint: v4)
        case "ramp":
            let v0 = try c.decode([Double].self, forKey: Key("r"))
            let v1 = try c.decode([Double].self, forKey: Key("g"))
            let v2 = try c.decode([Double].self, forKey: Key("b"))
            self = .ramp(r: v0, g: v1, b: v2)
        default:
            throw Swift.DecodingError.dataCorruptedError(forKey: Key("type"), in: c, debugDescription: "unknown Answer type \(tag)")
        }
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var c = encoder.container(keyedBy: Key.self)
        switch self {
        case .warmth(let v0, let v1, let v2, let v3, let v4):
            try c.encode("warmth", forKey: Key("type"))
            try c.encode(v0, forKey: Key("kelvin"))
            try c.encode(v1, forKey: Key("kelvinLabel"))
            try c.encode(v2, forKey: Key("dim"))
            try c.encode(v3, forKey: Key("gains"))
            try c.encode(v4, forKey: Key("tint"))
        case .ramp(let v0, let v1, let v2):
            try c.encode("ramp", forKey: Key("type"))
            try c.encode(v0, forKey: Key("r"))
            try c.encode(v1, forKey: Key("g"))
            try c.encode(v2, forKey: Key("b"))
        }
    }
}

public typealias GoodNightEngineStore = Store<GoodNightEngine>
